### PR TITLE
Add support for "htgroup" like file.

### PR DESCRIPTION
**Pull request by KLicheR**

### CODE REVIEW

**Comment by rlidwka** [comment]
Here is a better idea:

``` yaml
publisher: &publisher
  - user1
  - user2
  - user3

packages:
  'local-*':
    allow_access: $authenticated
    allow_publish: *publisher
```

You can already do groups with the existing `sinopia` yaml configuration file. So I don't see what benefit adding `htgroup` would gain.

**Comment by KLicheR** [comment]
To avoid reloading the app each time the configuration are changed.

The `htpasswd` and `htgroup` files can also be used to protect the web interface at the same time.

**Comment by rlidwka** [comment]
Well, there is a problem in this approach. Sinopia doesn't explicitly support groups. So what this commit is doing it adding aliases, like "`user1` could also publish documents available to `publisher`".

But somebody could register a user named `publisher` and get access to all the files this way. There is no protection against it.

> To avoid reloading the app each time the configuration are changed.

Maybe a feature request in sinopia to reload faster is in order here. Right now it stops completely and restarts, but we can do better.

> The htpasswd and htgroup files can also be used to protect the web interface at the same time.

This module is designed to be compatible with `nginx`, and `nginx` doesn't support `htgroup` as far as I know.

And `apache` will probably not work with out `htpasswd` anyway, because we rely on `crypt(3)` and apache works with `apache-md5` hashing. Not sure about that though, I didn't use apache for a long time.

**Comment by KLicheR** [comment]
I agree, this is probably not the best approach.

Thanks for your time.

**Pull request closed without merging**
